version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root